version: '3'

services:
  frontend:
    image: realworld-front-react
    container_name: realworld-front
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4100:4100
    environment:
      - CHOKIDAR_USEPOLLING=true
